"""create documents, sentences, labels

Revision ID: 15b40afa9006
Revises:
Create Date: 2026-05-25 12:24:02.300815

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "15b40afa9006"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sentences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "position", name="uq_sentence_position"),
    )
    op.create_index(op.f("ix_sentences_document_id"), "sentences", ["document_id"], unique=False)
    op.create_table(
        "labels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sentence_id", sa.Integer(), nullable=False),
        sa.Column("clause_type", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), server_default="MANUAL", nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "clause_type IN ('limitation_of_liability', 'termination_for_convenience', 'non_compete', 'confidentiality', 'governing_law', 'indemnification', 'force_majeure')",
            name="ck_label_clause_type",
        ),
        sa.CheckConstraint("source IN ('MANUAL', 'AUTO')", name="ck_label_source"),
        sa.ForeignKeyConstraint(["sentence_id"], ["sentences.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sentence_id", "clause_type", name="uq_label_sentence_clausetype"),
    )
    op.create_index(op.f("ix_labels_sentence_id"), "labels", ["sentence_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_labels_sentence_id"), table_name="labels")
    op.drop_table("labels")
    op.drop_index(op.f("ix_sentences_document_id"), table_name="sentences")
    op.drop_table("sentences")
    op.drop_table("documents")
    # ### end Alembic commands ###
